project:
  type: website

website:
  title: "Data Collection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: assignment1.qmd
        text: Assignment 1
      - href: assignment2.qmd
        text: Assignment 2
      - href: assignment3.qmd
        text: Assignment 3

format:
  html:
    theme: united
    css: styles.css
    toc: true



